### ISSUE TITLE
[BUG][Functional] Unable to deploy policies with conditions

### ISSUE THREAD

**Issue by papayamangoh** [aws-samples/aws-secure-environment-accelerator#980]
Bug reports which fail to provide the required information will be closed without action.

**Required Basic Info**
- Accelerator Version:  v1.5.0
- Install Type: clean
- Upgrade from version: N/A

**Describe the bug**
When using the AWS Secure Environment Accelerator to create or override an IAM policy as per the process documented below, any condition blocks in the IAM policy are dropped by the accelerator. The IAM policy deploys successfully but the condition statements are not present.

Process used to create an IAM policy: https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/src/mkdocs/docs/faq/index.md?plain=1#L129-L133

**Failure Info**
- What error messages have you identified, if any:  No error messages are present.
- What symptoms have you identified, if any: Perhaps missing condition statements here? https://github.com/aws-samples/aws-secure-environment-accelerator/blob/v1.5.1/src/deployments/cdk/src/common/iam-assets.ts#L58-L62

**Required files**
For example, with
Config: https://github.com/aws-samples/aws-secure-environment-accelerator/blob/main/reference-artifacts/SAMPLE_CONFIGS/config.ultralite-example.json 
boundary-policy.txt: Any boundary policy with conditions e.g. https://github.com/awsdocs/iam-user-guide/blob/main/doc_source/access_policies_boundaries.md?plain=1#L172-L250 (This file will need editing, including to match policy ARNs in config and account ID of environment being applied to)

**Steps To Reproduce**
1.  Locate the ASEA config S3 bucket. Create a folder (if it doesn't exist) called iam-policy. Upload the boundary-policy.txt file into the iam-policy folder.
2. Run the ASEA State Machine and wait until completion.
3. Log in to the AWS console and see the IAM policy defined by boundary-policy.txt. It is missing the condition statement.

**Expected behavior**
The IAM policy, include conditions should be applied as configured in the file, or an error returned.

**Comment by Brian969** [comment]
- More readable versions of the documentation can be found [here](https://aws-samples.github.io/aws-secure-environment-accelerator/faq/#how-do-i-update-some-of-the-supplied-sample-configuration-items-found-in-reference-artifact-like-scps-and-iam-policies).
- You can't put permission boundaries within permission boundaries, they need to be applied to the IAM policy itself.
- On first glance - it appears you are using a policy as a boundary policy - i.e. creating a mini-circular loop.  You should define a POLICY in the config which points to your json file, and then reference the policy on their role.

**Comment by Brian969** [comment]
- please provide/attach your example boundary policy and the role policy that references it.

**Comment by laure-co** [comment]
Thank you @Brian969.
 
Please find attached an example boundary policy. [ExampleBoundaryPolicyWithCondition.txt](https://github.com/aws-samples/aws-secure-environment-accelerator/files/9010208/ExampleBoundaryPolicyWithCondition.txt)

This is an example config snippet with the role that references the boundary policy.
```
   iam:
      users: []
      policies:
        - policy-name: ExampleBoundaryPolicyWithCondition
          policy: ExampleBoundaryPolicyWithCondition.txt
      roles:
        - role: Condition-Test-Role
          type: ec2
          ssm-log-archive-write-access: true
          policies:
            - AmazonSSMManagedInstanceCore
            - AmazonSSMDirectoryServiceAccess
            - CloudWatchAgentServerPolicy
          boundary-policy: ExampleBoundaryPolicyWithCondition
```

With this setup, the Condition-Test-Role is deployed with the boundary policy, but the boundary policy JSON has the IAM condition statements stripped off. It could be caused by missing conditions here  https://github.com/aws-samples/aws-secure-environment-accelerator/blob/v1.5.1/src/deployments/cdk/src/common/iam-assets.ts#L58-L62
